let n1 = (Math.floor(Math.random()*89) + 10);
let n2 = (Math.floor(Math.random()*89) + 10);
let n3 = (Math.floor(Math.random()*89) + 10);
let n4 = (Math.floor(Math.random()*89) + 10);
let n5 = (Math.floor(Math.random()*89) + 10);
console.log("five two digit random values :"+ n1+" "+n2+" "+n3+" "+n4+" "+n5);
let sum = n1 + n2 + n3 + n4 + n5;
let average = sum / 5;
console.log("sum is : "+ sum);
console.log("average is : "+ average);